# -*- coding: utf-8 -*-
"""
This family file was auto-generated by $Id: 5a8f6e5bb98b892ec341ec090800122b5eee7d79 $
Configuration parameters:
  url = https://wikimediafoundation.org
  name = wikimediafondation

Please do not commit this to the Git repository!
"""

from pywikibot import family


class Family(family.Family):
    def __init__(self):
        family.Family.__init__(self)
        self.name = 'wmfwiki'
        self.langs = {
            'wmfwiki': 'wikimediafoundation.org',
        }

    def scriptpath(self, code):
        return {
            'wmfwiki': '/w',
        }[code]

    def version(self, code):
        return {
            'wmfwiki': u'1.24wmf21',
        }[code]
